# Generated by Django 3.0.6 on 2021-02-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
