# Generated by Django 3.0.6 on 2021-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210209_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
