# Generated by Django 3.0.6 on 2021-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_content_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.FloatField(),
        ),
    ]
