# Generated by Django 3.0.6 on 2021-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
    ]
