# Generated by Django 3.0.6 on 2021-02-09 20:42

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210210_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url',
            field=embed_video.fields.EmbedVideoField(default=0),
            preserve_default=False,
        ),
    ]
