# Generated by Django 3.0.6 on 2021-02-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210210_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
