# Generated by Django 3.0.6 on 2021-02-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment_com_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='url',
        ),
        migrations.AddField(
            model_name='episode',
            name='src',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
