# Generated by Django 3.0.6 on 2021-02-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210210_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-orderBy']},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-orderBy']},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-orderBy']},
        ),
    ]
