# Generated by Django 3.0.6 on 2021-02-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.SubCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
    ]
