# Generated by Django 3.0.6 on 2021-02-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210211_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seasons',
        ),
    ]
