# Generated by Django 3.0.6 on 2021-02-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_seasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('img1', models.ImageField(upload_to='prod_imgs/')),
                ('orderBy', models.FloatField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Content')),
            ],
            options={
                'ordering': ['-orderBy'],
            },
        ),
    ]
