# Generated by Django 3.0.6 on 2021-02-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_seasons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seasons',
            new_name='Season',
        ),
    ]
