# Generated by Django 3.0.6 on 2021-02-11 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_episode_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('orderBy', models.FloatField()),
            ],
            options={
                'ordering': ['-orderBy'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='prod_imgs/')),
                ('release_date', models.DateField()),
                ('src', models.TextField()),
                ('rating', models.FloatField()),
                ('orderBy', models.FloatField()),
            ],
            options={
                'ordering': ['-orderBy'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('img', models.ImageField(upload_to='prod_imgs/')),
                ('rating', models.FloatField()),
                ('orderBy', models.FloatField()),
            ],
            options={
                'ordering': ['-orderBy'],
            },
        ),
        migrations.CreateModel(
            name='SeriesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon_class', models.CharField(max_length=150)),
                ('orderBy', models.FloatField()),
            ],
            options={
                'ordering': ['-orderBy'],
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='content',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='content',
        ),
        migrations.RemoveField(
            model_name='season',
            name='content',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='MovieCategory',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='series',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SeriesCategory'),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MovieCategory'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Genre'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Series'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Series'),
            preserve_default=False,
        ),
    ]
