# Generated by Django 3.0.6 on 2021-02-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210212_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='movieCategory',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='category',
            new_name='seriesCategory',
        ),
    ]
