# Generated by Django 3.0.6 on 2021-02-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210212_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='seriesCategory',
            new_name='category',
        ),
    ]
