# Generated by Django 3.0.6 on 2021-02-12 22:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210213_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrival',
            name='src',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Playlist_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('img1', models.ImageField(upload_to='prod_imgs/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='prod_imgs/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='prod_imgs/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='prod_imgs/')),
                ('src', models.TextField()),
                ('orderBy', models.FloatField()),
                ('likes', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Series')),
            ],
            options={
                'ordering': ['-orderBy'],
            },
        ),
    ]
