# Generated by Django 3.0.6 on 2021-02-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210213_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='playlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Playlist_items'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Episode'),
        ),
    ]
