# Generated by Django 3.0.6 on 2021-02-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210213_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='img4',
        ),
        migrations.AddField(
            model_name='movie',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Season'),
            preserve_default=False,
        ),
    ]
