# Generated by Django 3.0.6 on 2021-02-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_comment_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='newarrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.NewArrival'),
        ),
    ]
