# Generated by Django 3.0.6 on 2021-02-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_genre_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoon',
            name='director',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='length',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='director',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='length',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='director',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='length',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='length',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriescategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='prod_imgs/'),
        ),
    ]
