# Generated by Django 3.0.6 on 2021-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20210216_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
