# Generated by Django 3.0.6 on 2021-02-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_movie_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=100)),
                ('character_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='prod_imgs/')),
                ('ComingSoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ComingSoon')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Movie')),
                ('newarrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.NewArrival')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Playlist')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Series')),
            ],
        ),
    ]
