# Generated by Django 3.0.6 on 2021-02-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_cast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cast',
            old_name='ComingSoon',
            new_name='comingsoon',
        ),
    ]
