# Generated by Django 3.0.6 on 2021-02-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20210216_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='img1',
            new_name='img',
        ),
    ]
