# Generated by Django 3.0.6 on 2021-02-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210216_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='playlist_items',
            old_name='img1',
            new_name='img',
        ),
    ]
