# Generated by Django 3.0.6 on 2021-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210216_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='img',
            field=models.ImageField(default=0, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviecategory',
            name='img',
            field=models.ImageField(default=0, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlistcategory',
            name='img',
            field=models.ImageField(default=0, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seriescategory',
            name='img',
            field=models.ImageField(default=0, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
    ]
