# Generated by Django 3.0.6 on 2021-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210216_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoon',
            name='trailer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='trailer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='trailer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='trailer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
