# Generated by Django 3.0.6 on 2021-02-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='length',
        ),
    ]
