# Generated by Django 3.0.6 on 2021-02-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_slider_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='bg_img',
            new_name='img',
        ),
    ]
