# Generated by Django 3.0.6 on 2021-02-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20210217_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comingsoon',
            old_name='trailer',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='trailer',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='newarrival',
            old_name='trailer',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='trailer',
            new_name='cast',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='trailer',
            new_name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='playlist_items',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='playlist_items',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='playlist_items',
            name='img4',
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='poster',
            field=models.ImageField(default=1, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='quality',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=1, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='poster',
            field=models.ImageField(default=1, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='quality',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='poster',
            field=models.ImageField(default=1, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='quality',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='poster',
            field=models.ImageField(default=1, upload_to='prod_imgs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='quality',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
