# Generated by Django 3.0.6 on 2021-02-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20210217_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoon',
            name='PG',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='PG',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newarrival',
            name='PG',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='PG',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='PG',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
