# Generated by Django 3.1.6 on 2021-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20210217_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
