# Generated by Django 3.1.6 on 2021-02-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20210217_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comingsoon',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='rating',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
