# Generated by Django 3.1.6 on 2021-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20210218_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingsoon',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newarrival',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
