# Generated by Django 3.1.6 on 2021-02-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20210219_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='src',
            field=models.TextField(blank=True),
        ),
    ]
