# Generated by Django 3.1.6 on 2021-02-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_movie_genre_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comingsoon',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='comingsoon',
            name='director',
        ),
        migrations.RemoveField(
            model_name='comingsoon',
            name='length',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='director',
        ),
        migrations.RemoveField(
            model_name='newarrival',
            name='length',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='director',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='length',
        ),
        migrations.RemoveField(
            model_name='series',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='series',
            name='director',
        ),
        migrations.RemoveField(
            model_name='series',
            name='length',
        ),
        migrations.RemoveField(
            model_name='series',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='PG',
        ),
    ]
