# Generated by Django 3.1.6 on 2021-02-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20210223_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_values',
        ),
    ]
