# Generated by Django 3.1.6 on 2021-02-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_auto_20210223_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='meta_name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='meta_name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='meta_name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
